.PHONY: clean
clean:: ## remove all build artifacts generated by `make all`
	@:

.PHONY: distclean
distclean:: ## remove all artifacts, caches, dependencies, settings and reset branch to remote (DANGEROUS!)
ifeq ($(FORCE),)
	$(call log,notice,">>> distclean would execute:")
	$(call log,info,  "    git reset --hard @{upstream}")
	$(call log,info,  "    git clean -fdx")
	$(call log,notice,">>> use make distclean FORCE=y to execute")
	@:
else
	git reset --hard @{upstream}
	git clean -fdx
endif

.PHONY: dep
dep: ## alias for install
dep: install

.PHONY: install
install:: ## prepare environment and install dependencies for all make targets
install:: $(MKF_COMMON)/Aptfile.sh
ifneq ($(call has-command,apt-get),)
	sudo $(MKF_COMMON)/Aptfile.sh $(MKF_COMMON)/Aptfile
else
ifneq ($(call has-command,brew),)
	brew bundle --file $(MKF_COMMON)/Brewfile --no-upgrade install
endif
endif

.PHONY: up
up: ## alias for update
up: update

.PHONY: update
update:: ## update environment and all dependencies to their latest version(s)
ifneq ($(call has-command,apt-get),)
	sudo apt-get -y update
	sudo apt-get -y dist-upgrade
	sudo $(MKF_COMMON)/Aptfile.sh $(MKF_COMMON)/Aptfile
else
ifneq ($(call has-command,brew),)
	brew bundle --file $(MKF_COMMON)/Brewfile install
endif
endif
