.PHONY: clean distclean install update

clean:: ## remove all build artifacts generated by `make all`
distclean:: ## remove all artifacts, caches, dependencies and settings
install:: ## prepare environment and install dependencies for all make targets
update:: ## update environment and all dependencies to their latest version(s)
